# Generated by Django 4.2.3 on 2023-07-16 05:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_description_customuser_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='github',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.RegexValidator('^https://github.com/[a-zA-Z0-9_-]+/?$', 'Enter a valid GitHub profile URL.')]),
        ),
        migrations.AddField(
            model_name='customuser',
            name='linkedin',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.RegexValidator('^https://www.linkedin.com/in/[a-zA-Z0-9_-]+/?$', 'Enter a valid LinkedIn profile URL.')]),
        ),
        migrations.AddField(
            model_name='customuser',
            name='title',
            field=models.CharField(blank=True, error_messages={'max_length': 'Too long uwu'}, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='description',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile_images/'),
        ),
    ]
