# Generated by Django 4.2.3 on 2023-07-16 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_github_customuser_linkedin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='waifu',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
