# Generated by Django 4.2.3 on 2023-07-30 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_waifu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='description',
            field=models.TextField(blank=True, default='- Description -', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='github',
            field=models.URLField(blank=True, default='https://github.com/', null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='linkedin',
            field=models.URLField(blank=True, default='https://www.linkedin.com/in/', null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_images/default.jpg', null=True, upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='title',
            field=models.CharField(blank=True, default='- Title -', error_messages={'max_length': 'Too long uwu'}, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='waifu',
            field=models.ImageField(blank=True, default='profile_images/default_waifu.jpg', null=True, upload_to='profile_images/'),
        ),
    ]
